// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Loading.h"
#include "screens/ui_Tela_Principal.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * entrada_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

void ui_event____initial_actions0(lv_event_t * e);
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_fundo_png);    // assets/Fundo.png
LV_IMG_DECLARE(ui_img_logo_sea_doo_png);    // assets/Logo Sea Doo.png
LV_IMG_DECLARE(ui_img_2038326595);    // assets/Sem título.png
LV_IMG_DECLARE(ui_img_slider_battery2_png);    // assets/slider_battery2.png
LV_IMG_DECLARE(ui_img_gas_png);    // assets/gas.png
LV_IMG_DECLARE(ui_img_rpm_png);    // assets/RPM.png

// FONTS
LV_FONT_DECLARE(ui_font_Medium);
LV_FONT_DECLARE(ui_font_Number);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
