// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef UI_LOADING_H
#define UI_LOADING_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Loading
extern void ui_Loading_screen_init(void);
extern void ui_Loading_screen_destroy(void);
extern void ui_event_Loading(lv_event_t * e);
extern lv_obj_t * ui_Loading;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_logo;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

