// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Loading = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_logo = NULL;
// event funtions
void ui_event_Loading(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        entrada_Animation(ui_logo, 0);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(&ui_Tela_Principal, LV_SCR_LOAD_ANIM_NONE, 0, 2000, &ui_Tela_Principal_screen_init);
    }
}

// build funtions

void ui_Loading_screen_init(void)
{
    ui_Loading = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Loading, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image2 = lv_image_create(ui_Loading);
    lv_image_set_src(ui_Image2, &ui_img_fundo_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_logo = lv_image_create(ui_Loading);
    lv_image_set_src(ui_logo, &ui_img_logo_sea_doo_png);
    lv_obj_set_width(ui_logo, LV_SIZE_CONTENT);   /// 403
    lv_obj_set_height(ui_logo, LV_SIZE_CONTENT);    /// 78
    lv_obj_set_align(ui_logo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_logo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_logo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Loading, ui_event_Loading, LV_EVENT_ALL, NULL);

}

void ui_Loading_screen_destroy(void)
{
    if(ui_Loading) lv_obj_del(ui_Loading);

    // NULL screen variables
    ui_Loading = NULL;
    ui_Image2 = NULL;
    ui_logo = NULL;

}
