// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef UI_TELA_PRINCIPAL_H
#define UI_TELA_PRINCIPAL_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Tela_Principal
extern void ui_Tela_Principal_screen_init(void);
extern void ui_Tela_Principal_screen_destroy(void);
extern lv_obj_t * ui_Tela_Principal;
extern lv_obj_t * ui_Image3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

