// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Tela_Principal = NULL;
lv_obj_t * ui_Image3 = NULL;
// event funtions

// build funtions

void ui_Tela_Principal_screen_init(void)
{
    ui_Tela_Principal = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Tela_Principal, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image3 = lv_image_create(ui_Tela_Principal);
    lv_image_set_src(ui_Image3, &ui_img_913638935);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image3, 159);

}

void ui_Tela_Principal_screen_destroy(void)
{
    if(ui_Tela_Principal) lv_obj_del(ui_Tela_Principal);

    // NULL screen variables
    ui_Tela_Principal = NULL;
    ui_Image3 = NULL;

}
