// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Tela_Principal1 = NULL;
lv_obj_t * ui_Image4 = NULL;
lv_obj_t * ui_Temperatura1 = NULL;
lv_obj_t * ui_Gas1 = NULL;
lv_obj_t * ui_RPM1 = NULL;
lv_obj_t * ui_RPMBar1 = NULL;
lv_obj_t * ui_Slider1 = NULL;
lv_obj_t * ui_Km3 = NULL;
lv_obj_t * ui_Km4 = NULL;
lv_obj_t * ui_SliderKmSimulacao1 = NULL;
lv_obj_t * ui_kmh1 = NULL;
lv_obj_t * ui_Bateria1 = NULL;
lv_obj_t * ui_Hora1 = NULL;
lv_obj_t * ui_Image5 = NULL;
// event funtions
void ui_event_Slider1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_bar_increment(ui_RPMBar1, 1, LV_ANIM_ON);
    }
}

void ui_event_SliderKmSimulacao1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target_obj(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_Km3, target, "", "");
        _ui_slider_set_text_value(ui_Km4, target, "", "");
    }
}

// build funtions

void ui_Tela_Principal1_screen_init(void)
{
    ui_Tela_Principal1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Tela_Principal1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image4 = lv_image_create(ui_Tela_Principal1);
    lv_image_set_src(ui_Image4, &ui_img_2038326595);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image4, 165);

    ui_Temperatura1 = lv_slider_create(ui_Tela_Principal1);
    lv_slider_set_value(ui_Temperatura1, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Temperatura1) == LV_SLIDER_MODE_RANGE) lv_slider_set_start_value(ui_Temperatura1, 0,
                                                                                                  LV_ANIM_OFF);
    lv_obj_set_width(ui_Temperatura1, lv_pct(21));
    lv_obj_set_height(ui_Temperatura1, lv_pct(79));
    lv_obj_set_x(ui_Temperatura1, 377);
    lv_obj_set_y(ui_Temperatura1, 73);
    lv_obj_set_align(ui_Temperatura1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Temperatura1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Temperatura1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Temperatura1, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Temperatura1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Temperatura1, &ui_img_slider_battery2_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_Temperatura1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Temperatura1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Temperatura1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Temperatura1, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Temperatura1,
                                                                                                   lv_obj_get_style_pad_right(ui_Temperatura1, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Gas1 = lv_slider_create(ui_Tela_Principal1);
    lv_slider_set_value(ui_Gas1, 100, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Gas1) == LV_SLIDER_MODE_RANGE) lv_slider_set_start_value(ui_Gas1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Gas1, lv_pct(21));
    lv_obj_set_height(ui_Gas1, lv_pct(79));
    lv_obj_set_x(ui_Gas1, -388);
    lv_obj_set_y(ui_Gas1, 74);
    lv_obj_set_align(ui_Gas1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Gas1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Gas1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Gas1, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Gas1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Gas1, &ui_img_gas_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_Gas1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Gas1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Gas1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Gas1, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Gas1,
                                                                                           lv_obj_get_style_pad_right(ui_Gas1, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_RPM1 = lv_slider_create(ui_Tela_Principal1);
    lv_slider_set_value(ui_RPM1, 100, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_RPM1) == LV_SLIDER_MODE_RANGE) lv_slider_set_start_value(ui_RPM1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_RPM1, lv_pct(91));
    lv_obj_set_height(ui_RPM1, lv_pct(9));
    lv_obj_set_x(ui_RPM1, -4);
    lv_obj_set_y(ui_RPM1, -223);
    lv_obj_set_align(ui_RPM1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_RPM1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RPM1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_RPM1, LV_GRAD_DIR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_RPM1, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RPM1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_RPM1, &ui_img_rpm_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_RPM1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_RPM1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RPM1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_RPM1, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_RPM1,
                                                                                           lv_obj_get_style_pad_right(ui_RPM1, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_RPMBar1 = lv_bar_create(ui_Tela_Principal1);
    lv_bar_set_value(ui_RPMBar1, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_RPMBar1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_RPMBar1, 748);
    lv_obj_set_height(ui_RPMBar1, 187);
    lv_obj_set_x(ui_RPMBar1, -7);
    lv_obj_set_y(ui_RPMBar1, -136);
    lv_obj_set_align(ui_RPMBar1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_RPMBar1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RPMBar1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_RPMBar1, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RPMBar1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_RPMBar1, &ui_img_rpm_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_RPMBar1, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_RPMBar1,
                                                                                              lv_obj_get_style_pad_right(ui_RPMBar1, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Slider1 = lv_slider_create(ui_Tela_Principal1);
    lv_slider_set_value(ui_Slider1, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_start_value(ui_Slider1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider1, 141);
    lv_obj_set_height(ui_Slider1, 10);
    lv_obj_set_x(ui_Slider1, -215);
    lv_obj_set_y(ui_Slider1, 132);
    lv_obj_set_align(ui_Slider1, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Slider1, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Slider1,
                                                                                              lv_obj_get_style_pad_right(ui_Slider1, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Km3 = lv_label_create(ui_Tela_Principal1);
    lv_obj_set_width(ui_Km3, 319);
    lv_obj_set_height(ui_Km3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Km3, -90);
    lv_obj_set_y(ui_Km3, 13);
    lv_obj_set_align(ui_Km3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Km3, "0");
    lv_obj_set_style_text_color(ui_Km3, lv_color_hex(0x57F0ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Km3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Km3, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Km3, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Km3, &ui_font_Number, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Km4 = lv_label_create(ui_Tela_Principal1);
    lv_obj_set_width(ui_Km4, 341);
    lv_obj_set_height(ui_Km4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Km4, -110);
    lv_obj_set_y(ui_Km4, 13);
    lv_obj_set_align(ui_Km4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Km4, "0");
    lv_obj_set_style_text_color(ui_Km4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Km4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Km4, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Km4, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Km4, &ui_font_Number, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderKmSimulacao1 = lv_slider_create(ui_Tela_Principal1);
    lv_slider_set_range(ui_SliderKmSimulacao1, 0, 250);
    lv_slider_set_value(ui_SliderKmSimulacao1, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderKmSimulacao1) == LV_SLIDER_MODE_RANGE) lv_slider_set_start_value(ui_SliderKmSimulacao1,
                                                                                                        0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderKmSimulacao1, 150);
    lv_obj_set_height(ui_SliderKmSimulacao1, 10);
    lv_obj_set_x(ui_SliderKmSimulacao1, 155);
    lv_obj_set_y(ui_SliderKmSimulacao1, 129);
    lv_obj_set_align(ui_SliderKmSimulacao1, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_SliderKmSimulacao1, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_SliderKmSimulacao1,
                                                                                                         lv_obj_get_style_pad_right(ui_SliderKmSimulacao1, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_kmh1 = lv_label_create(ui_Tela_Principal1);
    lv_obj_set_width(ui_kmh1, 224);
    lv_obj_set_height(ui_kmh1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_kmh1, 110);
    lv_obj_set_y(ui_kmh1, 69);
    lv_obj_set_align(ui_kmh1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_kmh1, "km/h");
    lv_obj_set_style_text_color(ui_kmh1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_kmh1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_kmh1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_kmh1, &ui_font_Medium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bateria1 = lv_label_create(ui_Tela_Principal1);
    lv_obj_set_width(ui_Bateria1, 224);
    lv_obj_set_height(ui_Bateria1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Bateria1, -354);
    lv_obj_set_y(ui_Bateria1, -229);
    lv_obj_set_align(ui_Bateria1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Bateria1, "12.6V");
    lv_obj_set_style_text_color(ui_Bateria1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Bateria1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Bateria1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Bateria1, &ui_font_Medium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Hora1 = lv_label_create(ui_Tela_Principal1);
    lv_obj_set_width(ui_Hora1, 224);
    lv_obj_set_height(ui_Hora1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Hora1, 337);
    lv_obj_set_y(ui_Hora1, -229);
    lv_obj_set_align(ui_Hora1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Hora1, "12:45");
    lv_obj_set_style_text_color(ui_Hora1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Hora1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Hora1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Hora1, &ui_font_Medium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image5 = lv_image_create(ui_Tela_Principal1);
    lv_image_set_src(ui_Image5, &ui_img_2038326595);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 1662
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 945
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Slider1, ui_event_Slider1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderKmSimulacao1, ui_event_SliderKmSimulacao1, LV_EVENT_ALL, NULL);

}

void ui_Tela_Principal1_screen_destroy(void)
{
    if(ui_Tela_Principal1) lv_obj_del(ui_Tela_Principal1);

    // NULL screen variables
    ui_Tela_Principal1 = NULL;
    ui_Image4 = NULL;
    ui_Temperatura1 = NULL;
    ui_Gas1 = NULL;
    ui_RPM1 = NULL;
    ui_RPMBar1 = NULL;
    ui_Slider1 = NULL;
    ui_Km3 = NULL;
    ui_Km4 = NULL;
    ui_SliderKmSimulacao1 = NULL;
    ui_kmh1 = NULL;
    ui_Bateria1 = NULL;
    ui_Hora1 = NULL;
    ui_Image5 = NULL;

}
