// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef UI_TELA_PRINCIPAL1_H
#define UI_TELA_PRINCIPAL1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Tela_Principal1
extern void ui_Tela_Principal1_screen_init(void);
extern void ui_Tela_Principal1_screen_destroy(void);
extern lv_obj_t * ui_Tela_Principal1;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Temperatura1;
extern lv_obj_t * ui_Gas1;
extern lv_obj_t * ui_RPM1;
extern lv_obj_t * ui_RPMBar1;
extern void ui_event_Slider1(lv_event_t * e);
extern lv_obj_t * ui_Slider1;
extern lv_obj_t * ui_Km3;
extern lv_obj_t * ui_Km4;
extern void ui_event_SliderKmSimulacao1(lv_event_t * e);
extern lv_obj_t * ui_SliderKmSimulacao1;
extern lv_obj_t * ui_kmh1;
extern lv_obj_t * ui_Bateria1;
extern lv_obj_t * ui_Hora1;
extern lv_obj_t * ui_Image5;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

